### ISSUE TITLE
Redact our pixel to rem conversion.

### ISSUE THREAD

**Issue by codeviking** [allenai/ant-design#59]
@jonborchardt and I discussed `antd` in some detail. We determined that it'd likely be best if we embraced their use of pixels, rather than trying to change it (which we've already partially done).

While the use of pixels for font-size and line-height is bad-practice (as it's not accessible), trying to change it will only increase the likelihood of bugs and make it harder for us to merge changes from upstream.

We should accordingly yank out the work we've done thus far to execute this conversion. @jonborchardt is likely the best person to tackle this since he implemented the original changes.

**Comment by jonborchardt** [comment]
done
